"""Live trading data models.

These models implement the Execution Gate contract defined in
crypto-entry-analysis SKILL.md:

  - Gate status: PASS / WATCH_ONLY / REJECT
  - Checks: liquidity, funding, orderbook impact, ATR stop-loss,
            R:R, position cap, repeat-signal cooldown
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class GateStatus(str, Enum):
    """Final execution gate verdict."""

    PASS = "PASS"
    WATCH_ONLY = "WATCH_ONLY"
    REJECT = "REJECT"


class SignalDirection(str, Enum):
    """Trade direction."""

    LONG = "LONG"
    SHORT = "SHORT"


@dataclass
class ExecutionGateCheck:
    """Result of a single gate check."""

    name: str
    passed: bool
    detail: str = ""


@dataclass
class ExecutionGateResult:
    """Aggregated execution gate report.

    All checks must pass for a PASS verdict. WATCH_ONLY means marginal
    conditions. REJECT means at least one hard block triggered.
    """

    symbol: str
    direction: SignalDirection
    status: GateStatus
    checks: list[ExecutionGateCheck] = field(default_factory=list)
    summary: str = ""

    def add_check(self, name: str, passed: bool, detail: str = "") -> None:
        self.checks.append(ExecutionGateCheck(name=name, passed=passed, detail=detail))

    @property
    def passed_checks(self) -> list[ExecutionGateCheck]:
        return [c for c in self.checks if c.passed]

    @property
    def failed_checks(self) -> list[ExecutionGateCheck]:
        return [c for c in self.checks if not c.passed]


@dataclass
class LiveSignal:
    """A trading signal produced by the crypto entry analysis pipeline.

    Phase 1 ranking produces candidate signals. Phase 2 analysis adds
    conviction and risk context. The Execution Gate must be applied
    before any live order.
    """

    symbol: str
    direction: SignalDirection
    score: int
    max_score: int = 10
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    target_prices: list[float] = field(default_factory=list)
    conviction: str = "LOW"
    risk_reward_ratio: Optional[float] = None
    atr_stop_distance: Optional[float] = None
    note: str = ""
    gate_result: Optional[ExecutionGateResult] = None

    @property
    def score_pct(self) -> str:
        return f"{self.score}/{self.max_score}"

    @property
    def is_watch_only(self) -> bool:
        return self.gate_result is not None and self.gate_result.status == GateStatus.WATCH_ONLY

    @property
    def is_rejected(self) -> bool:
        return self.gate_result is not None and self.gate_result.status == GateStatus.REJECT

    @property
    def confidence_label(self) -> str:
        if self.conviction == "HIGH":
            return "✅ HIGH"
        elif self.conviction == "MEDIUM":
            return "⚠️ MEDIUM"
        return "❌ LOW"


@dataclass
class Phase2Request:
    """Request for Agent Phase 2 deep analysis.

    Generated by TradingScheduler for signals that pass Phase 1 filtering.
    Agent consumes these requests to load specific analysis dimensions.
    """

    symbol: str
    direction: str  # "LONG" or "SHORT"
    score: int
    tier: str  # "fast_track" (score ≥ 7) or "enhanced" (score 5-6)
    dims: list[str] = field(default_factory=list)
    entry_price: float = 0.0
    change_24h: float = 0.0
    rsi_1h: float = 50.0


@dataclass
class ScheduleReport:
    """Output of a single TradingScheduler run_once() cycle.

    Consumed by Agent tool (live_trading_tool.py) to present results
    and trigger Phase 2 analysis.
    """

    rankings: list[dict[str, object]] = field(default_factory=list)
    phase2_requests: list[Phase2Request] = field(default_factory=list)
    watchlist: list[dict[str, object]] = field(default_factory=list)
    btc_status: str = "CONDUCTION_OK"
    active_positions: int = 0
    trading_enabled: bool = False
    scan_time_ms: float = 0.0
    filtered_count: int = 0
